# Generated by Django 4.1 on 2022-08-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='best',
            field=models.BooleanField(default=False),
        ),
    ]
