# Generated by Django 4.1 on 2022-08-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_telpon', models.PositiveIntegerField()),
            ],
        ),
    ]
