# Generated by Django 4.1 on 2022-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='img_url',
            field=models.CharField(max_length=100),
        ),
    ]
