# Generated by Django 4.1 on 2022-08-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_reseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='img',
            field=models.FileField(upload_to='produk/'),
        ),
    ]
